[build]
  publish = "."

[[redirects]]
  from = "/build"
  to = "/build.html"
  status = 200

[[redirects]]
  from = "/features"
  to = "/features.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

# API calls redirect to builder service
[[redirects]]
  from = "/api/*"
  to = "https://insightful-perception-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"